export const developmentHospitals = [
  {
    slug: "city-hospital",
    name: "City Hospital",
    hospitalType: "general",
    address: "Sector 12, Chandigarh",
    city: "Chandigarh",
    state: "Chandigarh",
    latitude: 30.7415,
    longitude: 76.7683,
    description: "Sample nearby hospital record for development and API testing.",
    emergencyAvailable: true,
  },
  {
    slug: "government-hospital",
    name: "Government Hospital",
    hospitalType: "government",
    address: "Sector 16, Chandigarh",
    city: "Chandigarh",
    state: "Chandigarh",
    latitude: 30.7521,
    longitude: 76.7794,
    description: "Sample public hospital record for development and API testing.",
    emergencyAvailable: true,
  },
  {
    slug: "north-trauma-centre",
    name: "North Trauma Centre",
    hospitalType: "trauma_center",
    address: "Industrial Area Phase 2, Chandigarh",
    city: "Chandigarh",
    state: "Chandigarh",
    latitude: 30.7054,
    longitude: 76.8012,
    description: "Sample trauma-centre record for development and API testing.",
    emergencyAvailable: false,
  },
];