import { ClipboardList, Search, Trash2 } from 'lucide-react'
import { useState } from 'react'
import AdminConfirmDialog from '../components/AdminConfirmDialog'
import Alert from '../components/Alert'
import Button from '../components/Button'
import Card from '../components/Card'
import StatusBadge from '../components/StatusBadge'
import { useAdminManagement } from '../context/AdminManagementContext'
import { incidentStatuses } from '../data/incidentData'

export default function AdminIncidentsPage() {
  const { incidents, updateIncident, removeIncident } = useAdminManagement(); const [query, setQuery] = useState(''); const [status, setStatus] = useState('All statuses'); const [selectedId, setSelectedId] = useState(incidents[0]?.id); const [confirm, setConfirm] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const filtered = incidents.filter((item) => `${item.id} ${item.location} ${item.type}`.toLowerCase().includes(query.toLowerCase()) && (status === 'All statuses' || item.status === status)); const selected = incidents.find((item) => item.id === selectedId)
  const changeStatus = async (event) => { setSaving(true); setError(''); try { await updateIncident(selected.id, { status: event.target.value }) } catch { setError('Could not update this incident.') } finally { setSaving(false) } }
  const remove = async () => { setSaving(true); try { await removeIncident(selected.id); setConfirm(false); setSelectedId(incidents.find((item) => item.id !== selected.id)?.id) } catch { setError('Could not archive this incident.') } finally { setSaving(false) } }
  return <div className="page-content admin-management-page"><AdminManagementHeader icon={ClipboardList} title="Incident management" subtitle="Review and update simulated incident records." /><Alert tone="info" title="Mock incident administration">Status changes are local demo actions. They do not contact responders or change citizen records.</Alert><div className="management-toolbar"><label className="incident-search"><Search size={17} /><span className="sr-only">Search incidents</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search ID, location, or type" /></label><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filter incidents by status"><option>All statuses</option>{incidentStatuses.map((item) => <option key={item}>{item}</option>)}</select></div><div className="management-grid"><Card className="management-list">{filtered.length ? filtered.map((item) => <button className={`management-list-row ${selectedId === item.id ? 'management-list-row--active' : ''}`} type="button" key={item.id} onClick={() => setSelectedId(item.id)}><span className="management-avatar"><ClipboardList size={17} /></span><span><strong>{item.type}</strong><small>{item.id} · {item.location}</small></span><StatusBadge label={item.status} /></button>) : <AdminEmpty text="No incidents found" />}</Card>{selected && <Card className="management-detail"><div className="management-detail-heading"><div><span className="muted-label">Incident detail</span><h2>{selected.type}</h2><small>{selected.id}</small></div><StatusBadge label={selected.status} /></div>{error && <Alert tone="error" title="Action failed">{error}</Alert>}<div className="management-facts"><span><small>Location</small><strong>{selected.location}</strong></span><span><small>Date</small><strong>{selected.date}</strong></span><span><small>Description</small><strong>{selected.description}</strong></span></div><label className="field"><span>Update status</span><select value={selected.status} onChange={changeStatus} disabled={saving}>{incidentStatuses.map((item) => <option key={item}>{item}</option>)}</select></label><div className="management-actions"><Button variant="danger" onClick={() => setConfirm(true)}><Trash2 size={15} /> Archive record</Button></div></Card>}</div>{confirm && <AdminConfirmDialog title="Archive incident record?" message={`Archive ${selected?.id || 'this incident'} from the admin list?`} confirmLabel="Archive record" loading={saving} onCancel={() => setConfirm(false)} onConfirm={remove} />}</div>
}

function AdminManagementHeader({ icon: Icon, title, subtitle }) { return <div className="page-header"><div><span className="eyebrow"><Icon size={14} /> Admin management</span><h1 className="page-title">{title}</h1><p className="page-subtitle">{subtitle}</p></div></div> }
function AdminEmpty({ text }) { return <div className="admin-empty"><ClipboardList size={20} /><span>{text}</span></div> }