import { Edit3, Search, Trash2, UserRound, UsersRound } from 'lucide-react'
import { useState } from 'react'
import AdminConfirmDialog from '../components/AdminConfirmDialog'
import Alert from '../components/Alert'
import Button from '../components/Button'
import Card from '../components/Card'
import StatusBadge from '../components/StatusBadge'
import { useAdminManagement } from '../context/AdminManagementContext'
import { adminResponderStatuses } from '../data/adminManagementData'

export default function AdminRespondersPage() {
  const { responders, updateResponder, removeResponder } = useAdminManagement(); const [query, setQuery] = useState(''); const [status, setStatus] = useState('All statuses'); const [selectedId, setSelectedId] = useState(responders[0]?.id); const [confirm, setConfirm] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const filtered = responders.filter((item) => `${item.name} ${item.zone}`.toLowerCase().includes(query.toLowerCase()) && (status === 'All statuses' || item.status === status)); const selected = responders.find((item) => item.id === selectedId)
  const updateStatus = async (event) => { setSaving(true); try { await updateResponder(selected.id, { status: event.target.value }) } catch { setError('Could not update responder status.') } finally { setSaving(false) } }; const remove = async () => { setSaving(true); try { await removeResponder(selected.id); setConfirm(false); setSelectedId(responders.find((item) => item.id !== selected.id)?.id) } catch { setError('Could not remove responder.') } finally { setSaving(false) } }
  return <div className="page-content admin-management-page"><AdminManagementHeader icon={UsersRound} title="Responder management" subtitle="Review demo responder profiles and availability." /><Alert tone="info" title="Mock responder administration">Responder states are simulated and do not represent a live team or dispatch system.</Alert><div className="management-toolbar"><label className="incident-search"><Search size={17} /><span className="sr-only">Search responders</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search name or zone" /></label><select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filter responders by status"><option>All statuses</option>{adminResponderStatuses.map((item) => <option key={item}>{item}</option>)}</select></div><div className="management-grid"><Card className="management-list">{filtered.length ? filtered.map((item) => <button className={`management-list-row ${selectedId === item.id ? 'management-list-row--active' : ''}`} type="button" key={item.id} onClick={() => setSelectedId(item.id)}><span className="management-avatar"><UserRound size={17} /></span><span><strong>{item.name}</strong><small>{item.zone} · {item.assigned} assignments</small></span><StatusBadge label={item.status} /></button>) : <AdminEmpty text="No responders found" />}</Card>{selected && <Card className="management-detail"><div className="management-detail-heading"><div><span className="muted-label">Responder detail</span><h2>{selected.name}</h2><small>{selected.identifier}</small></div><StatusBadge label={selected.status} /></div>{error && <Alert tone="error" title="Action failed">{error}</Alert>}<div className="management-facts"><span><small>Zone</small><strong>{selected.zone}</strong></span><span><small>Assigned incidents</small><strong>{selected.assigned}</strong></span></div><label className="field"><span>Availability</span><select value={selected.status} onChange={updateStatus} disabled={saving}>{adminResponderStatuses.map((item) => <option key={item}>{item}</option>)}</select></label><div className="management-actions"><Button variant="secondary" onClick={() => setError('Edit controls are represented by the availability selector above.')}><Edit3 size={15} /> Edit profile</Button><Button variant="danger" onClick={() => setConfirm(true)}><Trash2 size={15} /> Remove</Button></div></Card>}</div>{confirm && <AdminConfirmDialog title="Remove responder profile?" message={`Remove ${selected?.name || 'this responder'} from the demo roster?`} confirmLabel="Remove responder" loading={saving} onCancel={() => setConfirm(false)} onConfirm={remove} />}</div>
}

function AdminManagementHeader({ icon: Icon, title, subtitle }) { return <div className="page-header"><div><span className="eyebrow"><Icon size={14} /> Admin management</span><h1 className="page-title">{title}</h1><p className="page-subtitle">{subtitle}</p></div></div> }
function AdminEmpty({ text }) { return <div className="admin-empty"><UsersRound size={20} /><span>{text}</span></div> }