import { AlertTriangle, Edit3, Phone, Plus, Trash2, UserRound, X } from 'lucide-react'
import { useState } from 'react'
import Alert from '../components/Alert'
import Button from '../components/Button'
import Card from '../components/Card'
import Input from '../components/Input'
import { useContacts } from '../context/ContactsContext'

const blankContact = { name: '', relation: '', phone: '', email: '' }

export default function ContactsPage() {
  const { contacts, addContact, updateContact, deleteContact } = useContacts()
  const [editing, setEditing] = useState(null)
  const [form, setForm] = useState(blankContact)
  const [deleteId, setDeleteId] = useState(null)
  const [error, setError] = useState('')
  const openAdd = () => { setEditing('new'); setForm(blankContact); setError('') }
  const openEdit = (contact) => { setEditing(contact.id); setForm({ name: contact.name, relation: contact.relation, phone: contact.phone, email: contact.email }); setError('') }
  const closeForm = () => setEditing(null)
  const update = (event) => setForm({ ...form, [event.target.name]: event.target.value })
  const save = (event) => { event.preventDefault(); if (!form.name.trim() || !form.relation.trim() || !form.phone.trim()) { setError('Name, relationship, and phone are required.'); return } editing === 'new' ? addContact(form) : updateContact(editing, form); closeForm() }
  return <div className="page-content contacts-page"><div className="page-header"><div><span className="eyebrow"><UserRound size={14} /> Safety network</span><h1 className="page-title">Emergency contacts</h1><p className="page-subtitle">Keep trusted people ready in this local demo list.</p></div><Button onClick={openAdd}><Plus size={17} /> Add contact</Button></div><div className="dashboard-demo-note"><span className="status-dot status-dot--info" /><span>Demo contact list</span><small>Changes are stored only in this browser session.</small></div>{editing && <ContactForm form={form} error={error} onChange={update} onSubmit={save} onCancel={closeForm} editing={editing !== 'new'} />}{contacts.length ? <div className="contact-list">{contacts.map((contact) => <Card className="contact-card" key={contact.id}><span className="contact-avatar"><UserRound size={21} /></span><div className="contact-card__body"><h2>{contact.name}</h2><span>{contact.relation}</span><p><Phone size={13} /> {contact.phone}</p>{contact.email && <small>{contact.email}</small>}</div><div className="contact-card__actions"><button className="icon-button" type="button" onClick={() => openEdit(contact)} aria-label={`Edit ${contact.name}`}><Edit3 size={16} /></button><button className="icon-button icon-button--danger" type="button" onClick={() => setDeleteId(contact.id)} aria-label={`Delete ${contact.name}`}><Trash2 size={16} /></button></div></Card>)}</div> : <Card className="notification-empty"><div className="placeholder-page__icon"><UserRound size={26} /></div><h2>No emergency contacts</h2><p>Add a trusted person to build your local safety network.</p></Card>}{deleteId && <DeleteDialog contact={contacts.find((contact) => contact.id === deleteId)} onConfirm={() => { deleteContact(deleteId); setDeleteId(null) }} onCancel={() => setDeleteId(null)} />}</div>
}

function ContactForm({ form, error, onChange, onSubmit, onCancel, editing }) { return <Card className="contact-form"><div className="card-heading"><div><span className="muted-label">{editing ? 'Edit contact' : 'New contact'}</span><h2>{editing ? 'Update trusted person' : 'Add trusted person'}</h2></div><button className="icon-button" type="button" onClick={onCancel} aria-label="Close form"><X size={17} /></button></div>{error && <Alert tone="error" title="Check contact details">{error}</Alert>}<form onSubmit={onSubmit} className="contact-form__grid"><Input label="Name" name="name" value={form.name} onChange={onChange} placeholder="Full name" /><Input label="Relationship" name="relation" value={form.relation} onChange={onChange} placeholder="Family, friend, neighbor" /><Input label="Phone" name="phone" value={form.phone} onChange={onChange} placeholder="Phone number" /><Input label="Email (optional)" name="email" value={form.email} onChange={onChange} placeholder="name@example.com" /><div className="report-actions contact-form__actions"><Button variant="ghost" type="button" onClick={onCancel}>Cancel</Button><Button type="submit">Save contact</Button></div></form></Card> }
function DeleteDialog({ contact, onConfirm, onCancel }) { return <div className="modal-backdrop" role="presentation"><Card className="delete-dialog" role="alertdialog" aria-modal="true" aria-labelledby="delete-contact-title"><div className="delete-dialog__icon"><AlertTriangle size={22} /></div><h2 id="delete-contact-title">Delete contact?</h2><p>Remove {contact?.name || 'this contact'} from your demo safety network?</p><div className="report-actions"><Button variant="ghost" onClick={onCancel}>Keep contact</Button><Button variant="danger" onClick={onConfirm}>Delete</Button></div></Card></div> }