import { ArrowRight, Bell, Hospital, MapPin, Phone, Plus, ShieldAlert } from 'lucide-react'
import { Link } from 'react-router-dom'
import Card from '../components/Card'
import Button from '../components/Button'
import StatusBadge from '../components/StatusBadge'
import MapContainer from '../components/MapContainer'

export default function DashboardPage() {
  return <div className="page-content"><div className="page-header"><div><h1 className="page-title">Good evening, Aryan</h1><p className="page-subtitle">Stay prepared. Your safety comes first.</p></div><Link to="/report-accident"><Button size="large"><ShieldAlert size={18} /> Report Accident</Button></Link></div><div className="dashboard-grid"><Card className="emergency-card"><div><span className="eyebrow">Emergency action</span><h2>Need help after a road accident?</h2><p>Share your location and incident details through the guided report.</p></div><Link to="/report-accident"><Button>Report Accident <ArrowRight size={16} /></Button></Link></Card><Card><div className="card-heading"><div><span className="muted-label">Current location</span><h3>Sector 12, Chandigarh</h3></div><MapPin color="var(--color-primary)" size={20} /></div><div className="dashboard-map"><MapContainer /></div></Card><Card><div className="card-heading"><div><span className="muted-label">Nearby hospitals</span><h3>3 hospitals found</h3></div><Hospital color="var(--color-primary)" size={20} /></div><div className="mini-list"><div><span className="mini-icon"><Hospital size={16} /></span><span><strong>City Hospital</strong><small>1.2 km away · Emergency</small></span><ArrowRight size={15} /></div><div><span className="mini-icon"><Hospital size={16} /></span><span><strong>Government Hospital</strong><small>2.4 km away · Emergency</small></span><ArrowRight size={15} /></div></div><Link className="text-link" to="/hospitals">View all hospitals</Link></Card><Card><div className="card-heading"><div><span className="muted-label">Notifications</span><h3>Recent updates</h3></div><Bell color="var(--color-primary)" size={20} /></div><div className="mini-list"><div><span className="notification-icon"><Bell size={15} /></span><span><strong>Welcome to the platform</strong><small>Demo notification · just now</small></span></div><div><span className="notification-icon"><Plus size={15} /></span><span><strong>Emergency contacts</strong><small>Add trusted contacts from your profile</small></span></div></div><Link className="text-link" to="/notifications">View notifications</Link></Card><Card><div className="card-heading"><div><span className="muted-label">Active incident</span><h3>Demo incident</h3></div><StatusBadge label="Reported" /></div><div className="incident-summary"><div><small>Incident ID</small><strong>ACC-2024-0520941</strong></div><div><small>Location</small><strong>Sector 12, Chandigarh</strong></div></div><Link to="/incidents"><Button variant="secondary" size="small">View incident</Button></Link></Card><Card><div className="quick-action"><span className="quick-action__icon"><Phone size={19} /></span><div><strong>Emergency contacts</strong><small>Keep trusted people ready to reach.</small></div><Link to="/emergency-contacts"><ArrowRight size={18} /></Link></div></Card></div></div>
}
