import { Bell, ChevronRight, LockKeyhole, Palette, Settings as SettingsIcon, ShieldCheck, Volume2 } from 'lucide-react'
import { useState } from 'react'
import Card from '../components/Card'

export default function SettingsPage() {
  const [settings, setSettings] = useState({ notifications: true, incidentUpdates: true, sound: false })
  const toggle = (key) => setSettings((current) => ({ ...current, [key]: !current[key] }))
  return <div className="page-content settings-page"><div className="page-header"><div><span className="eyebrow"><SettingsIcon size={14} /> Preferences</span><h1 className="page-title">Settings</h1><p className="page-subtitle">Control your local demo experience.</p></div></div><div className="dashboard-demo-note"><span className="status-dot status-dot--info" /><span>Demo preferences</span><small>These controls affect this browser session only.</small></div><div className="settings-grid"><Card><div className="settings-section-heading"><Bell size={18} /><div><h2>Notifications</h2><p>Choose which demo updates you see.</p></div></div><SettingToggle icon={Bell} label="In-app notifications" detail="Show updates in the notification list" checked={settings.notifications} onChange={() => toggle('notifications')} /><SettingToggle icon={ShieldCheck} label="Incident updates" detail="Show simulated incident status changes" checked={settings.incidentUpdates} onChange={() => toggle('incidentUpdates')} /><SettingToggle icon={Volume2} label="Sound cues" detail="Play sound for future in-app alerts" checked={settings.sound} onChange={() => toggle('sound')} /></Card><Card><div className="settings-section-heading"><Palette size={18} /><div><h2>Appearance</h2><p>Visual preferences for this demo.</p></div></div><div className="settings-choice"><span><strong>Theme</strong><small>Light theme is active</small></span><select defaultValue="light" aria-label="Theme preference"><option value="light">Light</option><option value="system" disabled>System (later)</option></select></div></Card><Card><div className="settings-section-heading"><LockKeyhole size={18} /><div><h2>Account & security</h2><p>Security actions are prepared for a future backend.</p></div></div><button className="settings-link" type="button"><span><strong>Password</strong><small>Password management will be connected later</small></span><ChevronRight size={17} /></button><button className="settings-link" type="button"><span><strong>Privacy</strong><small>Review demo data handling</small></span><ChevronRight size={17} /></button></Card></div></div>
}

function SettingToggle({ icon: Icon, label, detail, checked, onChange }) { return <label className="setting-toggle"><span className="setting-toggle__icon"><Icon size={16} /></span><span><strong>{label}</strong><small>{detail}</small></span><input type="checkbox" checked={checked} onChange={onChange} /><span className="toggle-track" aria-hidden="true"><span /></span></label> }